services:
  stable-diffusion-webui-deck:
    image: rocm/pytorch:latest
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
    restart: no
    command: ["/conf/startup-webui.sh"]
    devices:
      - "/dev/kfd:/dev/kfd" # remove this line if running on non ROCm
      - "/dev/dri/renderD129"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./data/home-webui:/root
      - ./models:/root/models
      - ./outputs:/root/outputs
      - ./conf:/conf
    environment:
      - DOCKER_INSTANCE=webui
      - PYTHON_VERSION=${PYTHON_VERSION}
      - ROCM_VERSION=${ROCM_VERSION}
      - ROOT_DIR=${ROOT_DIR}
      - WEBUI_PORT=${WEBUI_PORT}
      - REFORGE_PORT=${REFORGE_PORT}
